config/routes.rb
VoiceQuiz::Application.routes.draw do
  resources :questions

  get "home/index"
  get "home/process_answer"

end

app/models/question.rb
class Question < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
require "twilio-ruby"

class HomeController < ApplicationController

  # base URL of this application
  # BASE_URL = "http://localhost:3000/home"
  # BASE_URL = "http://ec2-23-21-156-76.compute-1.amazonaws.com/home"

  if Rails.env.production?
	BASE_URL = "http://ec2-23-21-156-76.compute-1.amazonaws.com/home"
  else  
	BASE_URL = "http://localhost:3000/home"
  end


  def index
	@post_to = BASE_URL + '/process_answer'

	@questions = Question.all

	if cookies[:cookie_data]
		@cookie_data = cookies[:cookie_data].split(",").map { |s| s.to_i }

		#increment current question index to iterate to the next question, unless we have been asked to repeat the current question
		@cookie_data[0] += 1 unless params['repeat_question'] == '1'		
		@current_question_index = @cookie_data[0]
		@current_question = @questions[@current_question_index]

		if params['repeat_question'] == '1'
			@repeat_question_rendering = true
		end

		#update the cookie
		cookies[:cookie_data] = @cookie_data.join(",")
	else
		@current_question_index = 0
		@current_question = @questions[@current_question_index]

		# cookie does not exist yet, create it here with the sole data element representing the current question index
		cookies[:cookie_data] = @current_question_index

		@render_intro = true
	end

	render :action => "ask_question.xml.builder"
  end

  def process_answer
	if !params['Digits'] or params['Digits'] == '0' or !['1','2','3','4'].member?(params['Digits'])
		redirect_to BASE_URL + '/index?repeat_question=1'
    		return
  	end

	@cookie_data = cookies[:cookie_data].split(",").map { |s| s.to_i }
	@current_question_index = @cookie_data[0]
	@current_question = Question.all[@current_question_index]
	@correct_answer = @current_question.answer

	@answer = "Option " + params['Digits']

	if (@answer != @correct_answer)
		if @cookie_data.length > 1
			# this means there was a wrong answer already
			# so, increment the count of wrong answers; this will be the second element in the cookie data array
			@cookie_data[1] += 1

		else
			# as the cookie data array has only one element, this must be the first wrong answer
			# add the count of wrong answers, i.e. 1, to the cookie data array
			@cookie_data << 1
		end
		
		# add the index of the current question to the list of wrongly answered questions
		@cookie_data << @current_question_index

		# now put the array back into a string and update the cookie
		cookies[:cookie_data] = @cookie_data.join(",")
	end 

	@total_number_of_questions = Question.count
	@current_question_index = @current_question_index + 1
	if (@current_question_index < @total_number_of_questions)
		redirect_to :action => 'index'
		return
	end

	# now the quiz is done, compute total score and render it
	if @cookie_data.length > 1
		@total_wrong_answers = @cookie_data[1]
		@result = "#{((@total_number_of_questions - @total_wrong_answers).to_f/@total_number_of_questions.to_f * 100.0).round}%"		
	else
		@result = "100%"
	end

	# delete cookies
	cookies.delete :cookie_data
	#cookies.delete :current_question
	#cookies.delete :wrong_answers

	render :action => "render_report.xml.builder"
	
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @questions }
    end
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @question = Question.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/new
  # GET /questions/new.json
  def new
    @question = Question.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/1/edit
  def edit
    @question = Question.find(params[:id])
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(params[:question])

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render json: @question, status: :created, location: @question }
      else
        format.html { render action: "new" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /questions/1
  # PUT /questions/1.json
  def update
    @question = Question.find(params[:id])

    respond_to do |format|
      if @question.update_attributes(params[:question])
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    respond_to do |format|
      format.html { redirect_to questions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VoiceQuiz</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :q_text, 'The Question' %><br />
    <%= f.text_field :q_text %>
  </div>
  <div class="field">
    <%= f.label :option_1 %><br />
    <%= f.text_field :option_1 %>
  </div>
  <div class="field">
    <%= f.label :option_2 %><br />
    <%= f.text_field :option_2 %>
  </div>
  <div class="field">
    <%= f.label :option_3 %><br />
    <%= f.text_field :option_3 %>
  </div>
  <div class="field">
    <%= f.label :option_4 %><br />
    <%= f.text_field :option_4 %>
  </div>
  <div class="field">
    <%= f.label :answer, 'And the correct answer is' %><br />
    <%= f.select(:answer, [['Option 1', 'Option 1'],['Option 2', 'Option 2'], ['Option 3', 'Option 3'], ['Option 4', 'Option 4']]) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<h1>Listing questions</h1>

<table>
  <tr>
    <th>The Question</th>
    <th>Option 1</th>
    <th>Option 2</th>
    <th>Option 3</th>
    <th>Option 4</th>
    <th>The Answer</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @questions.each do |question| %>
  <tr>
    <td><%= question.q_text %></td>
    <td><%= question.option_1 %></td>
    <td><%= question.option_2 %></td>
    <td><%= question.option_3 %></td>
    <td><%= question.option_4 %></td>
    <td><%= question.answer %></td>
    <td><%= link_to 'Show', question %></td>
    <td><%= link_to 'Edit', edit_question_path(question) %></td>
    <td><%= link_to 'Destroy', question, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>New question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>The Question:</b>
  <%= @question.q_text %>
</p>

<p>
  <b>Option 1:</b>
  <%= @question.option_1 %>
</p>

<p>
  <b>Option 2:</b>
  <%= @question.option_2 %>
</p>

<p>
  <b>Option 3:</b>
  <%= @question.option_3 %>
</p>

<p>
  <b>Option 4:</b>
  <%= @question.option_4 %>
</p>

<p>
  <b>The Answer:</b>
  <%= @question.answer %>
</p>


<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>